### ISSUE TITLE
关于 int8 算子请教

### ISSUE THREAD

**Issue by zhexinli** [ThisisBillhe/torch_quantizer#2]
hi 大佬，你这个工作很强，同为做量化的，很羡慕会写 cuda 实现自定义量化算子的

有两点问题想请教下：
1. 你的 conv 是用 cublass 实现的，请教下为什么选了 cublass 呢？比如 cudnn 中的 conv 也支持 int8，是否有考虑过调 cudnn 呢？
2. 在 cuda 代码中我似乎只看到了 dequant 算子，请问 input 的 quantize 是在哪里做的呢？weight  在 convert 后是 static 的 int8，但是模型中的 activation 应该还是 fp16 或者 fp32 的吧？

**Comment by ThisisBillhe** [comment]
Hi zhexin. 
1. 使用cudnn可能会有进一步性能提升，但由于边际效应，最后在整个网络层面的加速不会很大。目前瓶颈主要在quant/dequant阶段耗时比较大。
2. quantize可以参考[这里](https://github.com/ThisisBillhe/torch_quantizer/blob/041908ecdbce24788af5c71ea7cbf1a17a716fb7/torch_quantizer/src/quant_layer.py#L106)

**Comment by zhexinli** [comment]
明白了，谢谢大佬~
